inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 6.0.4

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - academiccommons_dev
    - academiccommons_test
    - academiccommons_prod
