# Template for blacklight.yml.
# blacklight.yml is used by Blacklight.

development:
  adapter: solr
  url: http://127.0.0.1:8983/solr/development

test:
  adapter: solr
  url: http://127.0.0.1:8993/solr/test
