# Copy this file to config/fedora.yml
default: &default
  user: fedoraAdmin
  password: fedoraAdmin

development:
  <<: *default
  url: http://localhost:8080/fedora

test:
  <<: *default
  url: http://localhost:9080/fedora
