# Copy this file to config/fedora.yml

development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora

test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:9080/fedora
