cron_errors: example@library.columbia.edu
index_api_key: api_key_for_metadata_editor_app
secret_key_base: SOMETHINGSOMETHINGSOMETHING
ga:
  user: google_analytics_user
  password: google_analytics_password
okcomputer:
  user: monitis
  password: monitis_pass
sword:
  url: http://example.com/sword
  user: sword_user
  password: sword_password
hyacinth:
  url: http://example.com
iiif:
  urls:
  - http://example.com/iiif/2
wowza:
  # NOTE: client_ip_override is only used locally during development because the IP comes through as localhost
  # client_ip_override: 'YOUR IP ADDRESS'
  host: 'example.com'
  port: 1935
  ssl_port: 8443
  token_prefix: 'wowza'
  shared_secret: 'EXAMPLE_SECRET'
  token_lifetime: 10800
  wowza_application_for_file_protocol_resources: 'WOWZA_APPLICATION_NAME_1'
  wowza_bucket_to_application_mapping_for_s3_resources:
    bucket-a: 'WOWZA_APPLICATION_NAME_2'
    bucket-b: 'WOWZA_APPLICATION_NAME_3'
