cron_errors: example@library.columbia.edu
index_api_key: api_key_for_metadata_editor_app
secret_key_base: SOMETHINGSOMETHINGSOMETHING
ga:
  user: google_analytics_user
  password: google_analytics_password
okcomputer:
  user: monitis
  password: monitis_pass
sword:
  url: http://example.com/sword
  user: sword_user
  password: sword_password
hyacinth:
  url: http://example.com
iiif:
  urls:
  - http://example.com/iiif/2
wowza:
  host: videos.example.com
  port: 1935
  ssl_port: 8443
  application: digital-access
  token_prefix: wowza
  shared_secret: password
  token_lifetime: 10800
